polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailsView.as_view(), name='details'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

pollsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib import admin

# Create your models here.


class Question(models.Model) :
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    @admin.display(
        boolean = True,
        ordering = pub_date,
        description = 'Was published recently?'
    )


    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        
    def __str__(self):
        return self.question_text 

    

class Choice(models.Model) :
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render

# Views .py file contains the view classes for the Index, Details and Results views and the functionality for voting

from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

# Index view displays a list of the 5 most recent questions by publication date
class IndexView(generic.ListView):
    template_name = 'polls/index.html' # load in template
    context_object_name = 'latest_question_list' # object name to display override

    # Overriding the get_queryset method to display the questions by date (top 5 most recent)
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

# Details view to display the question selected in detail
class DetailsView(generic.DetailView):
    # Overriding the displayed model and the template 
    model = Question
    template_name = 'polls/details.html'

# Results view to display voting results
class ResultsView(generic.DetailView):
    # Overriding the displayed model and the template 
    model = Question
    template_name = 'polls/results.html'

# Vote function to add a vote to an answer choice
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id) # find the question selected or throw a 404

    # Handle the error in choices (No answer chosen)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice']) # assign the question choice to selected and only change data with post
    except (KeyError, Choice.DoesNotExist):

        return render(request, 'polls/details.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })

    else: 
        selected_choice.votes += 1 # increment vote count by one 
        selected_choice.save() # save changes 
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,))) # redirect to avoid refreshes double counting

polls/templates/polls/details.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My test page</title>
    {% load static %}

    <link rel = 'stylesheet' type = 'text/css' href = "{% static 'polls/style.css' %}">
  </head>
  <body>
      <!-- Voting form to run the polls vote function -->
      <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %} <p><strong>{{error_message}}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type = 'radio' name = 'choice' id = 'choice{{forloop.counter}}' value = '{{choice.id}}'>
                <label for = 'choice{{forloop.counter}}'> {{choice.choice_text}} </label> <br>
            {% endfor %}
        </fieldset>
        <input type = 'submit' value = 'Vote'>
      </form>
    </body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My test page</title>
    {% load static %}

    <link rel = 'stylesheet' type = 'text/css' href = "{% static 'polls/style.css' %}">
  </head>
  <body>
      <h1>Poll Questions: </h1> 

    {% if latest_question_list %}

        <ul>
            {% for question in latest_question_list %}
            <li><a href="{% url 'polls:details' question.id %}">{{ question.question_text }} (Asked on: {{question.pub_date}})</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p> No polls available. </p>
    {% endif %}
    <p>Click on a poll to find out more information or to vote!</p>

    </body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}

    <link rel = 'stylesheet' type = 'text/css' href = "{% static 'polls/style.css' %}">
  </head>
  <body>
      <h1> {{question.question_text }} </h1>
      <ul>
        {% for choice in question.choice_set.all %}

            <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
        {% endfor %}
        </ul>

        <a href = "{% url 'polls:details' question.id %}">Vote again?</a>
    </body>
</html>